config/routes.rb
Flashfunders::Application.routes.draw do
  concern :showable_new do
    get :show, on: :member, action: :new
  end

  concern :showable_edit do
    get :show, on: :member, action: :edit
  end

  root to: 'home#show'

  get 'converted_show', to: 'home#converted_show'

  devise_for :users, controllers: { sessions: 'sessions', registrations: 'registrations', confirmations: 'confirmations', passwords: 'passwords', omniauth_callbacks: 'omniauth' }

  devise_scope :user do
    put '/users/confirm', to: 'confirmations#confirm', as: :user_confirm
    get '/users/log_me_out', to: 'sessions#log_me_out', as: :user_log_me_out
    get '/users/logout', to: 'sessions#logout', as: :user_logout

    namespace :api, defaults: { format: :json } do
      get '/users/session_info', to: '/sessions#session_info', as: :user_session_info
    end
  end

  get 'user/email_consent', to: 'email_consent#new'
  post 'user/email_consent', to: 'email_consent#create'
  get 'sign/:investment_uuid', to: 'docusign_bypass#sign'
  get 'issuer_sign/:investment_uuid', to: 'docusign_bypass#issuer_sign'
  get 'sign_success', to: 'docusign_bypass#success', as: :sign_success
  get 'sign_redirect', to: 'docusign_bypass#redirect', as: :sign_redirect
  get 'investment_agreement/:investment_uuid', to: 'docusign_bypass#agreement', as: :investment_agreement

  get '/impersonate/user/:user_id', to: 'impersonations#create', as: :impersonate
  delete '/impersonate/user/revert', to: 'impersonations#destroy', as: :revert_impersonate

  resource :issuer_applications, only: [:new, :create], concerns: [:showable_new] do
    get 'success'
    get 'recreate'
  end

  resource :dashboard, only: :show do
    resources :investments, only: [:index], controller: 'investments' do
      member do
        get :download_docs
        put :cancel_investment
      end
    end
    resources :conversations, only: [:index, :show, :create], controller: 'messages'
  end

  resource :subscriptions, only: [:create]
  get 'subscribe', to: 'subscriptions#new', as: :subscribe
  post 'dismiss', to: 'subscriptions#dismiss', as: :dismiss

  namespace :issuer do
    namespace :editor do
      resources :details, only: [:edit, :update], concerns: [:showable_edit]
      resources :pitches, only: [:edit, :update], concerns: [:showable_edit]
      resources :questions, only: [:edit, :update], concerns: [:showable_edit]
      resources :documents, only: [:edit, :update], concerns: [:showable_edit]
      resources :stakeholders, only: [:edit, :update], concerns: [:showable_edit]
    end
    resources :dashboard, controller: :dashboard, only: :show do
      get 'active_investments'
      get 'investment_activity', action: 'export_csv'
    end
    get 'change_context', controller: 'issuer'
  end

  resources :offering, controller: :offerings, only: :show do
    resource :investment_flow, controller: 'investment_flow/investments', except: [:destroy, :show] do
      resource :fund, controller: 'investment_flow/funds', only: [:new, :create, :edit, :update], concerns: [:showable_new] do
        get '/complete', action: 'complete'
      end
    end

    resource :investment, controller: 'invest/investments', except: [:destroy, :show] do
      get 'recreate'
      post '/update_payment', action: 'update_payment'
      post '/resend_verification', action: 'resend_verification'
    end
    namespace :invest do
      namespace :accreditation do
        resource :new, controller: :new, only: [:new, :create, :edit, :update], concerns: [:showable_new]
        resource :verified, controller: :verified, only: [:new, :create], concerns: [:showable_new]
      end
      resource :investment_profile, only: [:new, :create, :edit], concerns: [:showable_new]
      resource :investment_documents, only: [:show] do
        post '/accept', action: 'accept'
        get '/docusign_handler', action: 'docusign_handler'
        get '/docusign_redirect', action: 'docusign_redirect'
      end

      resource :fund, only: [:new, :create, :edit, :update], concerns: [:showable_new] do
        get '/complete', action: 'complete'
      end

    end

    resources :messages, controller: :offering_messages, only: [:create]
    resources :comment_forms, controller: :offering_comment_forms, only: [:create, :destroy]
    resource :follower, controller: :offering_followers, only: [:update, :destroy] do
      get 'follow', as: :redirect
    end
  end

  resources :third_party_qualifications, only: [:edit, :update], concerns: [:showable_edit] do
    get :decline, on: :member
  end

  resource :browse, only: :show
  resources :contact_forms, only: :create

  get '/terms', to: 'static#tos', as: :terms
  get '/terms_of_use', to: 'static#tos', as: nil
  get '/privacy', to: 'static#privacy', as: :privacy
  get '/privacy_policy', to: 'static#privacy', as: nil
  get '/email_disclaimer', to: 'static#email_disclaimer'
  get '/email_disclaimer_to_investor', to: 'static#email_disclaimer_to_investor'
  get '/email_disclaimer_to_issuer', to: 'static#email_disclaimer_to_issuer'
  get '/cip_notice', to: 'static#cip_notice'
  get '/unsubscribe', to: 'static#unsubscribe', as: :unsubscribe
  get '/contact', to: 'static#contact', as: :contact
  get '/get_started', to: 'static#get_started', as: :get_started
  get '/faq', to: 'static#faq_investor', as: :faq
  get '/team', to: 'static#team', as: :team
  get '/press', to: 'static#press', as: :press
  get '/electronic_consent', to: 'static#econsent', as: :econsent
  get '/sitemap', to: 'static#sitemap', as: :site_map

  if Rails.env.production?
    get '/blog', to: redirect('http://blog.flashfunders.com'), as: :blog
  else
    get '/blog', to: redirect('http://blog.flashdough.com'), as: :blog
  end
  get '/embedded_footer', to: 'iframeable#footer'
  get '/embedded_header', to: 'iframeable#header'

  get '/flashfundersinsider', to: redirect("#{ENV['HUBSPOT_LANDING_DOMAIN']}/flashfundersinsider"), as: :digital_marketing_landing_page

  get '/what_is_flashfunders', to: 'static#investors', as: :what_is_flashfunders

  get '/investors', to: 'static#investors', as: :investors
  get '/investor_hub', to: 'static#investors', as: :investor_hub
  get '/investor_faq', to: 'static#faq_investor', as: :investor_faq
  get '/faq/investor', to: 'static#faq_investor', as: :faq_investor

  get '/startups', to: 'static#startups', as: :startups
  get '/startup_hub', to: 'static#startups', as: :startup_hub
  get '/startup_faq', to: 'static#faq_startup', as: :startup_faq
  get '/faq/startup', to: 'static#faq_startup', as: :faq_startup

  # obsoleted paths redirection
  get '/how_to_invest', to: redirect('faq/investor#how_to_invest_flow')
  get '/raise_capital', to: redirect('startups')
  get '/documents/Investors', to: redirect('faq/investor#general')
  get '/startup_requirements', to: redirect('faq/startup#general-what-are-the-requirements-to-raise-capital-on-flashfunders')
  get '/investor_terms', to: redirect('faq/investor#investor_requirements_and_rights')
  get '/investor_benefits', to: redirect('faq/investor#benefits_risks')
  get '/startup_terms', to: redirect('faq/startup#fundraising_details')
  get '/investor_how_to_invest', to: redirect('faq/investor#how_to_invest_flow')

  namespace :api, defaults: { format: :json } do
    resources :offerings, only: :show

    namespace :issuer do
      resources :offerings, only: :index
      namespace :analytics do
        get '/get_data', to: '/issuer/analytics#get_data'
      end
    end

    get '/regions', to: '/static#regions', as: :regions
    get '/lookup_routing_number', to: '/static#lookup_routing_number', as: :lookup_routing_number
  end

  get '/robots.txt', to: 'home#robots'

  unless Rails.env.production?
    get '/style_guide', to: 'static#style_guide', as: :style_guide
    get '/honeybadger', to: 'honeybadger#blow_up'
  end

  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_error'

  # This is a catch-all route - leave it at the bottom of the routes file so it
  # doesn't clobber any legitimate routes
  get '*path', to: 'offerings#vanity_show', constraints: OfferingsVanityConstraints.new, as: 'offering_vanity'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include AnalyticsTracker
  skip_before_filter :authenticate_user!
  before_action :expire_cache, only: [:show]

  def show
    @subscription = Subscription.new
    @offerings = Offering.visibility_public.where("rank IS NOT NULL AND closed_status != 2").order(:rank).map do |offering|
      OfferingPresenter.new(offering)
    end.reject { |offering| offering.closed_pending?  }.first(6)
    @placeholder_offerings = get_placeholder_offerings(@offerings, 3)

    track_facebook_pixel(ff_facebook_pixel_id, 'ViewContent')
    respond_to :html
  end

  def show_less
    render layout: 'stripped_layout'
  end

  def robots
    suffix = %w(production review).include?(Rails.env) ? Rails.env : 'default'

    robots = File.read(Rails.root + "config/robots/robots.#{suffix}.txt")
    render :text => robots, :layout => false, :content_type => "text/plain"
  end

  private

  def expire_cache
    expire_cache_if_recache
  end

end

app/views/home/_ff_broker.html.haml
.ff_broker
  %p
    Checkout the background of our broker-dealer, funding-portal, and investment professionals on
    = link_to 'FINRA BrokerCheck', 'http://brokercheck.finra.org/Firm/Summary/134742', title: 'FINRA BrokerCheck'

app/views/home/_ff_news.html.haml
.ff-news
  %h2= t('home.ff_news')
  %hr.medium-bottom-line
  .news-items
    %a.item{href: 'http://blog.flashfunders.com/raising-capital-how-do-i-find-investors', target: '_blank'}
      = image_tag 'home/blog-post-2.jpg'
      .filter
      %h3
        Raising Capital - How Do I Find Investors?
      .author
        .avatar
          = image_tag 'home/Matt@2x.png'
        %p.name
          by Matthew Lebo
        %p.date
          11/28/2016
    %a.item{href: 'http://blog.flashfunders.com/dos-and-donts-of-pr-for-equity-crowdfunding', target: '_blank'}
      = image_tag 'home/blog-post-3.jpg'
      .filter
      %h3
        Do's and Don'ts of PR for Equity Crowdfunding
      .author
        .avatar
          = image_tag 'home/ronjini.jpg'
        %p.name
          by Ronjini Joshua
        %p.date
          11/28/2016
    %a.item{href: 'http://blog.flashfunders.com/verizon-acquire-lqd-wifi', target: '_blank'}
      = image_tag 'home/blog-post-1.jpg'
      .filter
      %h3
        Funded On FlashFunders: Verizon Acquires LQD WiFi
      .author
        .avatar
          = image_tag 'home/Matt@2x.png'
        %p.name
          by Matthew Lebo
        %p.date
          11/17/2016
  = link_to(t('home.read_more'), blog_path, class: 'thin-btn-outline btn-medium')

app/views/home/_header.html.haml
%header{role: 'banner', class: "#{'homepage' if home_page?}"}
  .top-nav
    %a.burger-menu.js-burger-menu{ href: "#" }
    .logo
      %a{:href => root_path, :title => "FlashFunders Home"}
        = image_tag 'FFLogo_2x.png', alt: 'FlashFunders Home', class: "large-logo blue"
        = image_tag 'home/FF_Logo_white.svg', alt: 'FlashFunders Home', class: "large-logo white"
    %nav.primary-nav.js-nav{:role => "navigation"}
      .closer
      %a.close-menu.js-burger-menu{ href: "#"}
      %ul
        - if current_user
          %li.user-login.toggle-user-menu.user-icon
          %li.user-login.toggle-user-menu.with-separator
            Hi #{current_user.forename}
            %small= current_user.email
          .offering-choice
            - offering_title_tabs.count > 1 && offering_title_tabs.each do |offering_tab|
              %li.nav-offering{ class: "#{offering_tab[:current_offering]}" }
                %a{ href: offering_tab[:dashboard_path], class: 'nav-icon nav-text', title: offering_tab[:name]}
                  %input{ type: :radio, class: "custom-radio", name: 'offerings', checked: offering_tab[:current_offering] == 'current-offering', disabled: true }
                  = offering_tab[:name]

        - else
          %li.user-login
            - if @within_blog
              = link_to t('nav.main_links.sign_in'), new_user_session_path(return_to: blog_path), class: 'nav-items--link sign-in continue-banner-hide', target: '_parent'
            - else
              = link_to t('nav.main_links.sign_in'), '#', class: 'nav-items--link sign-in continue-banner-hide', data: {toggle: 'modal', target: '#new-session-modal'}, title: t('nav.main_links.sign_in')
          %li.user-login.with-separator
            - if @within_blog
              = link_to t('nav.main_links.sign_up'), new_user_registration_path(return_to: blog_path), class: 'join-us nav-items--link sign-in continue-banner-hide', target: '_parent'
            - else
              = link_to t('nav.main_links.sign_up'), '#', class: 'join-us nav-items--link sign-in continue-banner-hide', data: {toggle: 'modal', target: '#new-registration-modal'}, title: t('nav.main_links.sign_up')
        = generate_header_menus
        - if current_user
          %ul.user-menu
            - offering_title_tabs.count > 1 && offering_title_tabs.each do |offering_tab|
              %li.nav-offering{ class: "#{offering_tab[:current_offering]}" }
                = link_to(offering_tab[:name], offering_tab[:dashboard_path], class: 'nav-icon nav-text', title: offering_tab[:name])
            %li.user-email{ class: "#{offering_title_tabs.count <= 1 ? 'border-bottom' : 'border-top' }" }
              %span= current_user.email
            %li= link_to 'Change Password', edit_user_registration_path, class: 'nav-password nav-icon nav-text', title: 'Change Password', target: link_target
            %li= link_to t('nav.sign_out'), destroy_user_session_path, class: 'nav-sign-out nav-icon nav-text', title: t('nav.sign_out'), target: link_target
-if content_for?(:below_header)
  = yield(:below_header)

app/views/home/_join_us.html.haml
.join-us
  %p
    %span
      Over $20,000,000 raised on FlashFunders.
    Interested in Raising Captital for your Business?
  = link_to(startups_path) do
    %button.btn-normal.btn-small= t('home.join_us')
%hr.bottom-line

app/views/home/_mission.html.haml
#mission-panel
  .container
    %h1= t('home.mission.title')
    .bottom-image

app/views/home/_offerings.html.haml
#browse-offerings
  .open-campaign
    .container
      %h2= t('browse.discovery.current_raise.home')
      %hr.medium-bottom-line
      .currently-raising
        = render partial: 'browse/offering_card', collection: @offerings
        = render partial: 'browse/placeholder_card', collection: @placeholder_offerings
      .centered.browse-more
        =link_to('Browse More Startups', browse_path, title: 'Browse More Startups', class: 'thin-btn-outline btn-medium')
      .successfully-funded
        %h2= t('browse.discovery.successfully_funded.home')
        %hr.medium-bottom-line
        = render partial: 'offerings_carousel'

app/views/home/_offerings_carousel.html.haml
- carousel_id = "#offerings-carousel"
.offerings-carousel
  .carousel.slide{ id: carousel_id.gsub('#', ''), data: { ride: 'carousel', interval: 5000 } }
    .carousel-inner
      - carousel_offerings.each_with_index do |offering, index|
        .item{ class: "#{'active' if index == 0}" }
          .item-tile
            = render partial: 'browse/offering_card', collection: [offering[:offering_presenter]]
          .item-detail
            .detail.one
              %p.num= '1'
              %p.text= offering[:bullets].first[:text].html_safe
              %p.date= offering[:bullets].first[:date]
            %ul
              %li
              %li
              %li
            .detail.two
              %p.num= '2'
              %p.text= offering[:bullets].last[:text].html_safe
              %p.date= offering[:bullets].last[:date]
    .control
      %a.left.carousel-control{ href: carousel_id, role: 'button', data: { slide: 'prev' } }
        = image_tag 'home/right_arrow.svg'
      %a.right.carousel-control{ href: carousel_id, role: 'button', data: { slide: 'next' } }
        = image_tag 'home/right_arrow.svg'

app/views/home/show.html.haml
- cache(@cache_key, skip_digest: true) do
  #home_show
    #home_header
      %video#video-bg{autoplay: "", loop: "", muted: "", playsinline: ""}
        %source{src: asset_path('FF_Video_Reel.mp4'), type: "video/mp4"}

      #filter-image
        .hero
          %h1.sh= t('home.title')
          = link_to(t('home.start_invest'), browse_path, class: 'btn-normal btn-medium')

    %main{:role => 'main'}
      - if @offerings.count == 0
        = render partial: 'mission'
      - else
        = render partial: 'offerings'

      .flashfunders-news
        = render partial: 'join_us'
        = render partial: 'ff_news'
        = render partial: 'shared/subscription_panel', locals: { form_id: 'home_new_subscription' }
        = render partial: 'ff_broker'

    .sponsors
      = render partial: 'shared/news_media'