config/routes.rb
Flashfunders::Application.routes.draw do
  concern :showable_new do
    get :show, on: :member, action: :new
  end

  concern :showable_edit do
    get :show, on: :member, action: :edit
  end

  root to: 'home#show'

  get 'converted_show', to: 'home#converted_show'

  devise_for :users, controllers: { sessions: 'sessions', registrations: 'registrations', confirmations: 'confirmations', passwords: 'passwords', omniauth_callbacks: 'omniauth' }

  devise_scope :user do
    put '/users/confirm', to: 'confirmations#confirm', as: :user_confirm
    get '/users/log_me_out', to: 'sessions#log_me_out', as: :user_log_me_out
    get '/users/logout', to: 'sessions#logout', as: :user_logout

    namespace :api, defaults: { format: :json } do
      get '/users/session_info', to: '/sessions#session_info', as: :user_session_info
    end
  end

  get 'user/email_consent', to: 'email_consent#new'
  post 'user/email_consent', to: 'email_consent#create'
  get 'sign/:investment_uuid', to: 'docusign_bypass#sign'
  get 'issuer_sign/:investment_uuid', to: 'docusign_bypass#issuer_sign'
  get 'sign_success', to: 'docusign_bypass#success', as: :sign_success
  get 'sign_redirect', to: 'docusign_bypass#redirect', as: :sign_redirect
  get 'investment_agreement/:investment_uuid', to: 'docusign_bypass#agreement', as: :investment_agreement

  get '/impersonate/user/:user_id', to: 'impersonations#create', as: :impersonate
  delete '/impersonate/user/revert', to: 'impersonations#destroy', as: :revert_impersonate

  resource :issuer_applications, only: [:new, :create], concerns: [:showable_new] do
    get 'success'
    get 'recreate'
  end

  resource :dashboard, only: :show do
    resources :investments, only: [:index], controller: 'investments' do
      member do
        get :download_docs
        put :cancel_investment
      end
    end
    resources :conversations, only: [:index, :show, :create], controller: 'messages'
  end

  resource :subscriptions, only: [:create]
  get 'subscribe', to: 'subscriptions#new', as: :subscribe
  post 'dismiss', to: 'subscriptions#dismiss', as: :dismiss

  namespace :issuer do
    namespace :editor do
      resources :details, only: [:edit, :update], concerns: [:showable_edit]
      resources :pitches, only: [:edit, :update], concerns: [:showable_edit]
      resources :questions, only: [:edit, :update], concerns: [:showable_edit]
      resources :documents, only: [:edit, :update], concerns: [:showable_edit]
      resources :stakeholders, only: [:edit, :update], concerns: [:showable_edit]
    end
    resources :dashboard, controller: :dashboard, only: :show do
      get 'active_investments'
      get 'investment_activity', action: 'export_csv'
    end
    get 'change_context', controller: 'issuer'
  end

  resources :offering, controller: :offerings, only: :show do
    resource :investment_flow, controller: 'investment_flow/investments', except: [:destroy, :show] do
      resource :fund, controller: 'investment_flow/funds', only: [:new, :create, :edit, :update], concerns: [:showable_new] do
        get '/complete', action: 'complete'
      end
    end

    resource :investment, controller: 'invest/investments', except: [:destroy, :show] do
      get 'recreate'
      post '/update_payment', action: 'update_payment'
      post '/resend_verification', action: 'resend_verification'
    end
    namespace :invest do
      namespace :accreditation do
        resource :new, controller: :new, only: [:new, :create, :edit, :update], concerns: [:showable_new]
        resource :verified, controller: :verified, only: [:new, :create], concerns: [:showable_new]
      end
      resource :investment_profile, only: [:new, :create, :edit], concerns: [:showable_new]
      resource :investment_documents, only: [:show] do
        post '/accept', action: 'accept'
        get '/docusign_handler', action: 'docusign_handler'
        get '/docusign_redirect', action: 'docusign_redirect'
      end

      resource :fund, only: [:new, :create, :edit, :update], concerns: [:showable_new] do
        get '/complete', action: 'complete'
      end

    end

    resources :messages, controller: :offering_messages, only: [:create]
    resources :comment_forms, controller: :offering_comment_forms, only: [:create, :destroy]
    resource :follower, controller: :offering_followers, only: [:update, :destroy] do
      get 'follow', as: :redirect
    end
  end

  resources :third_party_qualifications, only: [:edit, :update], concerns: [:showable_edit] do
    get :decline, on: :member
  end

  resource :browse, only: :show
  resources :contact_forms, only: :create

  get '/terms', to: 'static#tos', as: :terms
  get '/terms_of_use', to: 'static#tos', as: nil
  get '/privacy', to: 'static#privacy', as: :privacy
  get '/privacy_policy', to: 'static#privacy', as: nil
  get '/email_disclaimer', to: 'static#email_disclaimer'
  get '/email_disclaimer_to_investor', to: 'static#email_disclaimer_to_investor'
  get '/email_disclaimer_to_issuer', to: 'static#email_disclaimer_to_issuer'
  get '/cip_notice', to: 'static#cip_notice'
  get '/unsubscribe', to: 'static#unsubscribe', as: :unsubscribe
  get '/contact', to: 'static#contact', as: :contact
  get '/get_started', to: 'static#get_started', as: :get_started
  get '/faq', to: 'static#faq_investor', as: :faq
  get '/team', to: 'static#team', as: :team
  get '/press', to: 'static#press', as: :press
  get '/electronic_consent', to: 'static#econsent', as: :econsent
  get '/sitemap', to: 'static#sitemap', as: :site_map

  if Rails.env.production?
    get '/blog', to: redirect('http://blog.flashfunders.com'), as: :blog
  else
    get '/blog', to: redirect('http://blog.flashdough.com'), as: :blog
  end
  get '/embedded_footer', to: 'iframeable#footer'
  get '/embedded_header', to: 'iframeable#header'

  get '/flashfundersinsider', to: redirect("#{ENV['HUBSPOT_LANDING_DOMAIN']}/flashfundersinsider"), as: :digital_marketing_landing_page

  get '/what_is_flashfunders', to: 'static#investors', as: :what_is_flashfunders

  get '/investors', to: 'static#investors', as: :investors
  get '/investor_hub', to: 'static#investors', as: :investor_hub
  get '/investor_faq', to: 'static#faq_investor', as: :investor_faq
  get '/faq/investor', to: 'static#faq_investor', as: :faq_investor

  get '/startups', to: 'static#startups', as: :startups
  get '/startup_hub', to: 'static#startups', as: :startup_hub
  get '/startup_faq', to: 'static#faq_startup', as: :startup_faq
  get '/faq/startup', to: 'static#faq_startup', as: :faq_startup

  # obsoleted paths redirection
  get '/how_to_invest', to: redirect('faq/investor#how_to_invest_flow')
  get '/raise_capital', to: redirect('startups')
  get '/documents/Investors', to: redirect('faq/investor#general')
  get '/startup_requirements', to: redirect('faq/startup#general-what-are-the-requirements-to-raise-capital-on-flashfunders')
  get '/investor_terms', to: redirect('faq/investor#investor_requirements_and_rights')
  get '/investor_benefits', to: redirect('faq/investor#benefits_risks')
  get '/startup_terms', to: redirect('faq/startup#fundraising_details')
  get '/investor_how_to_invest', to: redirect('faq/investor#how_to_invest_flow')

  namespace :api, defaults: { format: :json } do
    resources :offerings, only: :show

    namespace :issuer do
      resources :offerings, only: :index
      namespace :analytics do
        get '/get_data', to: '/issuer/analytics#get_data'
      end
    end

    get '/regions', to: '/static#regions', as: :regions
    get '/lookup_routing_number', to: '/static#lookup_routing_number', as: :lookup_routing_number
  end

  get '/robots.txt', to: 'home#robots'

  unless Rails.env.production?
    get '/style_guide', to: 'static#style_guide', as: :style_guide
    get '/honeybadger', to: 'honeybadger#blow_up'
  end

  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_error'

  # This is a catch-all route - leave it at the bottom of the routes file so it
  # doesn't clobber any legitimate routes
  get '*path', to: 'offerings#vanity_show', constraints: OfferingsVanityConstraints.new, as: 'offering_vanity'
end

app/controllers/issuer/analytics_controller.rb
module Issuer

  class AnalyticsController < ApplicationController
    skip_before_filter :store_location
    skip_before_filter :track_visitor
    skip_before_filter :set_error_context
    skip_before_filter :flash

    before_action do
      @offering = set_offering_context(params[:id])
    end
    GA_EXPIRE_TIMEOUT = 3600
    GA_NAMESPACE = "GA"

    def get_data
      if @offering
        setup_dates

        data = cached_or_fresh(params)
        if data
          render json: { offering_id: @offering.id }.merge(data)
        else
          render nothing: true
        end
      else
        render nothing: true
      end
    end

    private

    def setup_dates

      offering_end_date = @offering.escrow_end_date || @offering.ends_at || Time.now

      date_start = params['start_date'].present? ? Date.parse(params['start_date']) : @offering.created_at.to_date
      date_end = params['end_date'].present? ? Date.parse(params['end_date']) : offering_end_date.to_date

      my_start_date = (date_start > @offering.created_at && date_start <= offering_end_date) ? date_start : @offering.created_at.to_date
      my_end_date = (date_end < offering_end_date && date_end >= @offering.created_at) ? date_end : offering_end_date

      if(my_start_date > my_end_date)
        my_start_date = @offering.created_at.to_date
        my_end_date = offering_end_date > my_start_date ? offering_end_date : Time.now
      end

      my_end_date = Date.today if my_end_date > Date.today

      @start_date = my_start_date.to_s
      @end_date = my_end_date.to_s

    end

    def analyzer
      @analyzer ||= IssuerAnalytics.new
    end

    def cached_or_fresh(params)
      ga_key = get_key(params)
      with_rescue { get_cached(ga_key) } || get_fresh(ga_key, params)
    end

    def get_fresh(ga_key, params)
      Rails.logger.info("getting fresh #{ga_key}")
      method = analyzer.method(params[:data_set])
      begin
        data = method.call(@start_date, @end_date, @offering, params)
      rescue Google::Apis::ServerError => e
        Honeybadger.notify e
        return nil
      end
      with_rescue do
        cache!(ga_key, data)
      end
      data
    end

    def get_key(params)
      key = "#{GA_NAMESPACE}/#{params[:data_set]}/offering:#{@offering.id}|start_date:#{@start_date}|end_date:#{@end_date}"
      key += "|frequency:#{params[:frequency]}" if params[:data_set] == "page_visit_info"
      key
    end

    def with_rescue
      begin
        yield
      rescue Redis::CannotConnectError => e
        Rails.logger.error e
        nil
      rescue e
        Honeybadger.notify e
        nil
      end
    end

    def get_cached(key)
      data = $redis.get(key)
      if data
        Rails.logger.info("hit - #{key}")
      else
        Rails.logger.info("miss - #{key}")
      end
      JSON.parse(data) if data
    end

    def cache!(key, val)
      $redis.set(key, val.to_json)
      $redis.expire(key, GA_EXPIRE_TIMEOUT)
      Rails.logger.info("caching #{key}")
    end

  end
end

app/controllers/issuer/dashboard_controller.rb
module Issuer
  class DashboardController < ApplicationController

    before_action do
      @offering = set_offering_context(params[:id])
    end

    ITEMS_PER_PAGE = 10
    UP_ARROW       = '&and;' #0x2304.chr
    DOWN_ARROW     = '&or;' #0x5e.chr

    def show
      if @offering
        set_params
        respond_to do |format|
          format.html do
            @offering_presenter = OfferingPresenter.new(@offering)
          end
          format.js do
            case params[:section]
              when 'investments'
                render partial: 'issuer/dashboard/panel_ajax', locals: { section: params[:section], data: @investment_data }
            end
          end
        end
      else
        render_404
      end
    end

    def export_csv
      csv_info = case params[:section]
        when 'investments'
          investment_activity_csv
        end

      send_data csv_info[:data], filename: csv_info[:filename]
    end

    private

    def set_params
      @investment_data = gen_params(:investments, investments,
                                    %w(started signed funded messages),
                                    params[:section] == 'investments' ? params : {})
      @offering.dashboard_last_viewed_at = Time.now
      @offering.save
    end

    def gen_params(kind, items, headers, params)
      number_to_display = (params[:count] || 0).to_i + ITEMS_PER_PAGE
      page              = params[:page] || 0
      sort_by           = params[:sort_by] || 'updated_at'
      sort_dir          = params[:sort_dir] || 'desc'
      sorted_items      = sort_items(items, sort_dir, sort_by)
      displayed         = [number_to_display, items.count].min

      build_params_hash(displayed, headers, items, kind, number_to_display, page, params, sort_by, sort_dir, sorted_items)
    end

    def build_params_hash(displayed, headers, items, kind, number_to_display, page, params, sort_by, sort_dir, sorted_items)
      { sort_by:      sort_by,
        sort_dir:     sort_dir,
        page:         page,
        remaining:    items.count - number_to_display,
        displayed:    displayed,
        headers:      headers,
        sort_headers: gen_sortable_headers(kind, sort_by, sort_dir),
        items:        Kaminari.paginate_array(sorted_items, total_count: sorted_items.count)
                        .page(page)
                        .per(displayed),
        last_viewed:  params[:last_viewed] || @offering.dashboard_last_viewed_at || Time.parse(I18n.t('issuer-dashboard.dawn'))
      }
    end

    def sort_items(items, sort_dir, sort_by)
      items.sort { |a, b|
        if sort_dir == 'asc'
          a.send(sort_by) <=> b.send(sort_by)
        else
          b.send(sort_by) <=> a.send(sort_by)
        end
      }
    end

    def include_user?(user)
      (user.email =~ /@flashfunders\.com/).nil? && !user.rejected?
    end

    def investments
      @all_investments ||= Investment.where(offering_id: @offering.id)
                             .select { |i| include_user?(i.user) }
                             .map { |i| InvestmentPresenter.new(i) }
    end

    def gen_sortable_headers(spec, current_column, current_dir)
      header_spec[spec].map do |h|
        sort_dir   = 'desc'
        sort_arrow = ''
        if current_column == h[:sort]
          if current_dir == 'desc'
            sort_dir   = 'asc'
            sort_arrow = '&nbsp;' + UP_ARROW
          else
            sort_arrow = '&nbsp;' + DOWN_ARROW
          end
        end
        { title: "#{h[:title]}#{sort_arrow}", sort_by: h[:sort], sort_dir: sort_dir, id: h[:title].parameterize.underscore, section: spec }
      end
    end

    def header_spec
      { investments:
               [{ title: 'last active', sort: 'updated_at' },
                { title: 'name', sort: 'investor_name' },
                { title: 'email', sort: 'investor_email' },
                { title: 'amount', sort: 'amount' }]
      }
    end

    def investment_activity_csv
      columns = (header_spec[:investments].map {|hash| hash[:title]} | %w(followed started\ investment signed funded))
      resources = sort_items(investments, params[:sort_dir], params[:sort_by])
      resources = resources + followers
      CSVGenerator::Base.new(:investment_activity, columns, resources, offering_name: @offering.company.name).csv_file
    end

    def followers
      OfferingFollower.follower.where(offering_id: @offering.id)
    end

  end
end

app/controllers/issuer/editor/base_controller.rb
module Issuer
  module Editor
    class BaseController < ApplicationController

      include FormAuditing
      helper :offering_editor

      private

      def auditor
        Auditor.new
      end

      def audit_params
        permitted_params
      end

    end
  end
end

app/controllers/issuer/editor/questions_controller.rb
module Issuer
  module Editor
    class QuestionsController < BaseController

      before_action :assign_offering

      def edit
      end

      def update
        if offering.update_attributes(permitted_params)
          audit_form!
          flash.notice = "Your changes have been saved"
          redirect_to edit_issuer_editor_question_path(offering)
        else
          flash.now.alert = "The following information is missing or invalid:"
          render :edit
        end
      end

      private

      def permitted_params
        return {} unless params[:faq]

        params[:faq].permit(
          investor_faqs_attributes: [
            :id, '_destroy', :question, :answer, :rank
          ]
        )
      end

      def assign_offering
        @offering ||= Offering.for_user(current_user)
          .includes(:company, :investor_faqs)
          .find(params[:id])
      end
      alias_method :offering, :assign_offering

    end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper

  def offering_title_tabs
    @title_tabs ||= find_offerings_for_user.map do |offering|
      {
        tab_code_name: offering.company.name,
        name: offering_tab_name(offering),
        dashboard_path: controller.change_context_path(offering.id),
        current_offering: get_offering_context == offering.id ? 'current-offering' : ''
      }
    end
  end

  private

  def find_offerings_for_user
    @offerings_for_user ||= Offering.for_user(current_user)
  end

  def unread_for_issuer_offerings
    @unread_for_issuer_offerings ||= OfferingMessage.unread_for_issuer(current_user.id)
  end

  def offering_tab_name(offering)
    "#{offering.company.name}#{unread_str(unread_for_issuer_offerings[offering.id].to_i)}"
  end

  def unread_str(unread)
    unread > 0 ? " (#{unread})" : ''
  end

  def get_offering_context
    cookies['_startup'].to_i
  end

end

app/views/issuer/dashboard/_investment.html.haml
.csv-export= link_to 'Export to .CSV', issuer_dashboard_investment_activity_path(sorting_info(data[:sort_headers]).merge(dashboard_id: @offering.id))
%table.responsive{id: "panel-issuer-#{section}"}
  %tbody
    %tr
      - data[:sort_headers].each do |header|
        %th.left
          = link_to header[:title].html_safe,
              issuer_dashboard_path(id: @offering.id, sort_by: header[:sort_by], sort_dir: header[:sort_dir],
                                    count: data[:displayed] - Issuer::DashboardController::ITEMS_PER_PAGE,
                                    page: data[:page], last_viewed: data[:last_viewed], section: section),
              remote: true, id: header[:id]
      - data[:headers].each do |heading|
        %th.centered= heading

    - data[:items].each do |investment|
      %tr{ class: ('highlight' if data[:last_viewed].blank? || investment.updated_at > data[:last_viewed]) }
        %td= investment.formatted_updated_at
        %td= investment.investor_name
        %td= investment.investor_email
        %td= investment.formatted_amount
        %td.centered
          .content-mobile
            .fa.fa-check-circle
          .content
            .fa.fa-check-circle{ data: { info_popover: 'true', title: 'Started', content: investment.created_at.try(:strftime, '%b %e, %Y %I:%M %P %Z') } }
        %td.centered
          - if investment.has_signed_docs?
            .content-mobile
              .fa.fa-check-circle
            .content
              .fa.fa-check-circle{ data: { info_popover: 'true', title: 'Docs Signed', content: investment.docs_signed_at.try(:strftime, '%b %e, %Y %I:%M %P %Z') } }
        %td.centered
          -if investment.escrowed?
            .content-mobile
              .fa.fa-check-circle
            .content
              .fa.fa-check-circle{ data: { info_popover: 'true', title: 'Funded', content: investment.escrowed_at.try(:strftime, '%b %e, %Y %I:%M %P %Z') } }
        %td.centered
          %a{  href:  dashboard_conversation_path(investment.offering_id, user_id: investment.user_uuid) }
            .fa.fa-comment

.footer
  .page-nav= paginate(data[:items], left: 1, right: 1, window: 4, remote: true,
                      params: { sort_by: data[:sort_by], sort_dir: data[:sort_dir], last_viewed: data[:last_viewed], section: section })
  .page-info= page_entries_info data[:items]
- if data[:remaining] > 0
  .footer-mobile
    = link_to I18n.t('issuer-dashboard.pagination.load-more'),
              issuer_dashboard_path(id: @offering.id, sort_by: data[:sort_by], sort_dir: data[:sort_dir],
                                    count: data[:displayed], last_viewed: data[:last_viewed], section: section),
              remote: true

app/views/issuer/dashboard/_panel.html.haml
.dashboard-panel{ id: "issuer-#{section}" }
  - if any_panel_data?(section, data)
    .well
      %h3= t("issuer-dashboard.#{section}.title")
      = render partial: section.to_s.singularize, locals: { section: section, data: data }
  - else
    = render partial: 'panel_blank', locals: { section: section }
  = render partial: 'panel_error', locals: { section: section }

app/views/issuer/dashboard/_panel_ajax.html.haml
var tableHtml = "#{escape_javascript( render partial: 'issuer/dashboard/panel', locals: { section: section, data: data } )}"
$("#issuer-#{section}").replaceWith(tableHtml);
FF.updateTables("panel-issuer-#{section}");
$('[data-info-popover]').each(function() { new FF.Popover(this); });

app/views/issuer/dashboard/_panel_blank.html.haml
%div{ id: "no-#{section}" }
  .well
    %h2= t("issuer-dashboard.#{section}.title")
    %table
      %tr
        %th= image_tag(t("issuer-dashboard.#{section}.icon"))
      %tr
        %td
          %h3= t("issuer-dashboard.#{section}.none")
      %tr
        %td= t("issuer-dashboard.#{section}.caption").html_safe

app/views/issuer/dashboard/_panel_error.html.haml
%div{ id: "error-retrieving-#{section}", class: "error-retrieving" }
  .well
    %table
      %tr
        %th= image_tag(I18n.t("issuer-dashboard.error-retrieving.icon"))
      %tr
        %td
          %h2= I18n.t("issuer-dashboard.error-retrieving.none")
      %tr
        %td= I18n.t("issuer-dashboard.error-retrieving.caption").html_safe

app/views/issuer/dashboard/_top_traffic.html.haml
#top-traffic.dashboard-panel{data: {end_date: @offering.escrow_end_date || @offering.ends_at, offering_start_date: @offering.created_at.strftime("%Y-%m-%d")}}
  .well
    .row-fluid.responsive
      .span9
        %h3= I18n.t("issuer-dashboard.top-traffic.title")
      .span3
        %select#top-traffic-dropdown.no-placeholder
    .empty
      .icon.top-traffic
      .title= t('issuer-dashboard.top-traffic.no-traffic.title')
      .subtitle= t('issuer-dashboard.top-traffic.no-traffic.subtitle')
    .stats-container
      .timeframe
        %span
      .totals
        %span.number
        %small
          = with_popover(t('issuer-dashboard.top-traffic.total-page-views'), t('issuer-dashboard.top-traffic.total-page-popover'), t('issuer-dashboard.top-traffic.total-page-views'))
      .items.row-fluid.responsive

app/views/issuer/dashboard/_traffic_overview.html.haml
= select 'pageview', :metrics, {'Pageviews' => "Pageviews", 'Unique Pageviews' => "UniquePageviews", 'Avg Time on Page' => "AvgTimeOnPage"}, { selected: "Pageviews" }, class: 'no-placeholder'
#date-ranges
  %ul
    %li.daily.active Daily
    %li.weekly Weekly
    %li.monthly Monthly
  #pageview-date-range-text
    %p
.with-data
  %canvas#traffic-chart
  .stats-container
    .totals
      %span.number
      %small#Pageviews-legend.active
        = with_popover(I18n.t('issuer-dashboard.traffic_overview.total-page-views'), t('issuer-dashboard.traffic_overview.total-page-views-popover'), t('issuer-dashboard.traffic_overview.total-page-views-popover-title'))
      %small#UniquePageviews-legend
        = with_popover(I18n.t('issuer-dashboard.traffic_overview.total-unique-page-views'), t('issuer-dashboard.traffic_overview.total-unique-page-views-popover'), t('issuer-dashboard.traffic_overview.total-unique-page-views-popover-title'))
      %small#AvgTimeOnPage-legend
        = with_popover(I18n.t('issuer-dashboard.traffic_overview.total-avg-time-on-page'), t('issuer-dashboard.traffic_overview.total-avg-time-on-page-popover'), t('issuer-dashboard.traffic_overview.total-avg-time-on-page-popover-title'))
.empty
  .icon.traffic_overview
  .title= t('issuer-dashboard.traffic_overview.no-traffic.title')
  .subtitle= t('issuer-dashboard.traffic_overview.no-traffic.subtitle').html_safe

app/views/issuer/dashboard/show.html.haml
#issuer-dashboard
  - title = "#{@offering_presenter.company_name} Dashboard"
  = content_for(:page_title, title)

  .title-bar
    %h2= title
    = link_to('View Offering', offering_short_path(@offering_presenter), class: 'title-link')
  #kpi-tiles
    .kpi-tile
      %span.raise
        .title= t('issuer-dashboard.tiles.raised.title')
        .value= @offering_presenter.formatted_accredited_balance
      %span.limits= t('issuer-dashboard.tiles.raised.limits', { min: @offering_presenter.minimum_investment_amount_display, max: @offering_presenter.maximum_total_investment_display}).html_safe
    .kpi-tile.investors
      .title= t('issuer-dashboard.tiles.investors.title')
      .value= @offering_presenter.number_of_investors
    .kpi-tile.daysleft
      .title= t('issuer-dashboard.tiles.days_left.title')
      .value= @offering_presenter.days_left

  = render partial: 'panel', locals: { section: :investments, data: @investment_data }
  = render partial: 'panel', locals: { section: :traffic_overview, data: {}  }
  = render partial: 'top_traffic'

  .footer-spacer