config/routes.rb
Flashfunders::Application.routes.draw do
  concern :showable_new do
    get :show, on: :member, action: :new
  end

  concern :showable_edit do
    get :show, on: :member, action: :edit
  end

  root to: 'home#show'

  get 'converted_show', to: 'home#converted_show'

  devise_for :users, controllers: { sessions: 'sessions', registrations: 'registrations', confirmations: 'confirmations', passwords: 'passwords', omniauth_callbacks: 'omniauth' }

  devise_scope :user do
    put '/users/confirm', to: 'confirmations#confirm', as: :user_confirm
    get '/users/log_me_out', to: 'sessions#log_me_out', as: :user_log_me_out
    get '/users/logout', to: 'sessions#logout', as: :user_logout

    namespace :api, defaults: { format: :json } do
      get '/users/session_info', to: '/sessions#session_info', as: :user_session_info
    end
  end

  get 'user/email_consent', to: 'email_consent#new'
  post 'user/email_consent', to: 'email_consent#create'
  get 'sign/:investment_uuid', to: 'docusign_bypass#sign'
  get 'issuer_sign/:investment_uuid', to: 'docusign_bypass#issuer_sign'
  get 'sign_success', to: 'docusign_bypass#success', as: :sign_success
  get 'sign_redirect', to: 'docusign_bypass#redirect', as: :sign_redirect
  get 'investment_agreement/:investment_uuid', to: 'docusign_bypass#agreement', as: :investment_agreement

  get '/impersonate/user/:user_id', to: 'impersonations#create', as: :impersonate
  delete '/impersonate/user/revert', to: 'impersonations#destroy', as: :revert_impersonate

  resource :issuer_applications, only: [:new, :create], concerns: [:showable_new] do
    get 'success'
    get 'recreate'
  end

  resource :dashboard, only: :show do
    resources :investments, only: [:index], controller: 'investments' do
      member do
        get :download_docs
        put :cancel_investment
      end
    end
    resources :conversations, only: [:index, :show, :create], controller: 'messages'
  end

  resource :subscriptions, only: [:create]
  get 'subscribe', to: 'subscriptions#new', as: :subscribe
  post 'dismiss', to: 'subscriptions#dismiss', as: :dismiss

  namespace :issuer do
    namespace :editor do
      resources :details, only: [:edit, :update], concerns: [:showable_edit]
      resources :pitches, only: [:edit, :update], concerns: [:showable_edit]
      resources :questions, only: [:edit, :update], concerns: [:showable_edit]
      resources :documents, only: [:edit, :update], concerns: [:showable_edit]
      resources :stakeholders, only: [:edit, :update], concerns: [:showable_edit]
    end
    resources :dashboard, controller: :dashboard, only: :show do
      get 'active_investments'
      get 'investment_activity', action: 'export_csv'
    end
    get 'change_context', controller: 'issuer'
  end

  resources :offering, controller: :offerings, only: :show do
    resource :investment_flow, controller: 'investment_flow/investments', except: [:destroy, :show] do
      resource :fund, controller: 'investment_flow/funds', only: [:new, :create, :edit, :update], concerns: [:showable_new] do
        get '/complete', action: 'complete'
      end
    end

    resource :investment, controller: 'invest/investments', except: [:destroy, :show] do
      get 'recreate'
      post '/update_payment', action: 'update_payment'
      post '/resend_verification', action: 'resend_verification'
    end
    namespace :invest do
      namespace :accreditation do
        resource :new, controller: :new, only: [:new, :create, :edit, :update], concerns: [:showable_new]
        resource :verified, controller: :verified, only: [:new, :create], concerns: [:showable_new]
      end
      resource :investment_profile, only: [:new, :create, :edit], concerns: [:showable_new]
      resource :investment_documents, only: [:show] do
        post '/accept', action: 'accept'
        get '/docusign_handler', action: 'docusign_handler'
        get '/docusign_redirect', action: 'docusign_redirect'
      end

      resource :fund, only: [:new, :create, :edit, :update], concerns: [:showable_new] do
        get '/complete', action: 'complete'
      end

    end

    resources :messages, controller: :offering_messages, only: [:create]
    resources :comment_forms, controller: :offering_comment_forms, only: [:create, :destroy]
    resource :follower, controller: :offering_followers, only: [:update, :destroy] do
      get 'follow', as: :redirect
    end
  end

  resources :third_party_qualifications, only: [:edit, :update], concerns: [:showable_edit] do
    get :decline, on: :member
  end

  resource :browse, only: :show
  resources :contact_forms, only: :create

  get '/terms', to: 'static#tos', as: :terms
  get '/terms_of_use', to: 'static#tos', as: nil
  get '/privacy', to: 'static#privacy', as: :privacy
  get '/privacy_policy', to: 'static#privacy', as: nil
  get '/email_disclaimer', to: 'static#email_disclaimer'
  get '/email_disclaimer_to_investor', to: 'static#email_disclaimer_to_investor'
  get '/email_disclaimer_to_issuer', to: 'static#email_disclaimer_to_issuer'
  get '/cip_notice', to: 'static#cip_notice'
  get '/unsubscribe', to: 'static#unsubscribe', as: :unsubscribe
  get '/contact', to: 'static#contact', as: :contact
  get '/get_started', to: 'static#get_started', as: :get_started
  get '/faq', to: 'static#faq_investor', as: :faq
  get '/team', to: 'static#team', as: :team
  get '/press', to: 'static#press', as: :press
  get '/electronic_consent', to: 'static#econsent', as: :econsent
  get '/sitemap', to: 'static#sitemap', as: :site_map

  if Rails.env.production?
    get '/blog', to: redirect('http://blog.flashfunders.com'), as: :blog
  else
    get '/blog', to: redirect('http://blog.flashdough.com'), as: :blog
  end
  get '/embedded_footer', to: 'iframeable#footer'
  get '/embedded_header', to: 'iframeable#header'

  get '/flashfundersinsider', to: redirect("#{ENV['HUBSPOT_LANDING_DOMAIN']}/flashfundersinsider"), as: :digital_marketing_landing_page

  get '/what_is_flashfunders', to: 'static#investors', as: :what_is_flashfunders

  get '/investors', to: 'static#investors', as: :investors
  get '/investor_hub', to: 'static#investors', as: :investor_hub
  get '/investor_faq', to: 'static#faq_investor', as: :investor_faq
  get '/faq/investor', to: 'static#faq_investor', as: :faq_investor

  get '/startups', to: 'static#startups', as: :startups
  get '/startup_hub', to: 'static#startups', as: :startup_hub
  get '/startup_faq', to: 'static#faq_startup', as: :startup_faq
  get '/faq/startup', to: 'static#faq_startup', as: :faq_startup

  # obsoleted paths redirection
  get '/how_to_invest', to: redirect('faq/investor#how_to_invest_flow')
  get '/raise_capital', to: redirect('startups')
  get '/documents/Investors', to: redirect('faq/investor#general')
  get '/startup_requirements', to: redirect('faq/startup#general-what-are-the-requirements-to-raise-capital-on-flashfunders')
  get '/investor_terms', to: redirect('faq/investor#investor_requirements_and_rights')
  get '/investor_benefits', to: redirect('faq/investor#benefits_risks')
  get '/startup_terms', to: redirect('faq/startup#fundraising_details')
  get '/investor_how_to_invest', to: redirect('faq/investor#how_to_invest_flow')

  namespace :api, defaults: { format: :json } do
    resources :offerings, only: :show

    namespace :issuer do
      resources :offerings, only: :index
      namespace :analytics do
        get '/get_data', to: '/issuer/analytics#get_data'
      end
    end

    get '/regions', to: '/static#regions', as: :regions
    get '/lookup_routing_number', to: '/static#lookup_routing_number', as: :lookup_routing_number
  end

  get '/robots.txt', to: 'home#robots'

  unless Rails.env.production?
    get '/style_guide', to: 'static#style_guide', as: :style_guide
    get '/honeybadger', to: 'honeybadger#blow_up'
  end

  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_error'

  # This is a catch-all route - leave it at the bottom of the routes file so it
  # doesn't clobber any legitimate routes
  get '*path', to: 'offerings#vanity_show', constraints: OfferingsVanityConstraints.new, as: 'offering_vanity'
end

app/models/stakeholder.rb
class Stakeholder < ActiveRecord::Base

  default_scope { order("rank ASC") }

  belongs_to :offering

  enum stakeholder_type_id: { team_member: 1, investor: 2 }

  after_create :update_notable_investor_if_necessary

  mount_uploader :avatar_photo, StakeholderUploader

  [:website, :facebook_url, :linkedin_url, :twitter_url].each do |url|
    validates url, web_url_format: true, allow_blank: true
  end

  def is_notable_investor=(val)
    @is_notable_investor = val.present?
    if persisted?
      offering.update_attribute('notable_investor_id', self.id)
    end
  end

  def is_notable_investor?
    return false if offering.nil?
    offering.notable_investor_id == self.id
  end
  alias_method :is_notable_investor, :is_notable_investor?

  private

  def update_notable_investor_if_necessary
    if @is_notable_investor
      offering.update_attribute('notable_investor_id', self.id)
    end
  end

end

app/controllers/issuer/editor/base_controller.rb
module Issuer
  module Editor
    class BaseController < ApplicationController

      include FormAuditing
      helper :offering_editor

      private

      def auditor
        Auditor.new
      end

      def audit_params
        permitted_params
      end

    end
  end
end

app/controllers/issuer/editor/details_controller.rb
module Issuer
  module Editor
    class DetailsController < BaseController

      before_action :assign_offering
      before_action :assign_uploader

      def edit
        offering.company ||= Company.new
      end

      def update
        if offering.update_attributes(permitted_params)
          audit_form!
          flash.notice = "Your changes have been saved"
          redirect_to edit_issuer_editor_detail_path
        else
          flash.now.alert = "The following information is missing or invalid:"
          render :edit
        end
      end

      private

      def permitted_params
        return {} unless params[:offering]

        params.require(:offering).permit(
          :public_contact_name, :tagline, :tagline_browse,
          :photo_swatch_key, :photo_logo_key, :photo_cover_key, :vanity_path, :photo_header_key,
          :facebook_pixel_id, :google_tracking_id,
          :google_adwords_conversion_id, :google_adwords_conversion_label,
          company_attributes: [:id, :name, :location, :website_url]
        )
      end

      def assign_offering
        @offering ||= Offering.for_user(current_user)
          .includes(:company)
          .find(params[:id])
      end
      alias_method :offering, :assign_offering

      def assign_uploader
        @uploader = Offering.new.photo_cover
        @uploader.success_action_status = '201'
      end

    end
  end
end

app/controllers/issuer/editor/documents_controller.rb
module Issuer
  module Editor
    class DocumentsController < BaseController

      before_action :assign_offering
      before_action :assign_uploader

      def edit
      end

      def update
        if offering.update_attributes(permitted_params)
          audit_form!
          flash.notice = "Your changes have been saved"
          redirect_to edit_issuer_editor_document_path(offering)
        else
          flash.now.alert = "The following information is missing or invalid:"
          render :edit
        end
      end

      private

      def permitted_params
        return {} unless params[:documents]

        params[:documents].permit(
          campaign_documents_attributes: [
            :id, '_destroy', :name, :document_new_key, :rank
          ],
          deal_documents_attributes: [
            :id, '_destroy', :name, :document_new_key, :rank, :description
          ]

        )
      end

      def assign_offering
        @offering ||= Offering.for_user(current_user)
          .includes(:company, :campaign_documents)
          .find(params[:id])
      end
      alias_method :offering, :assign_offering

      def assign_uploader
        @document_uploader = Document.new.document_new
        @document_uploader.success_action_status = '201'
      end

    end
  end
end

app/controllers/issuer/editor/pitches_controller.rb
module Issuer
  module Editor
    class PitchesController < BaseController

      before_action :assign_offering
      before_action :assign_uploader, only: [:edit, :update]

      def edit
      end

      def update
        if offering.update_attributes(permitted_params)
          audit_form!
          flash.notice = "Your changes have been saved"
          redirect_to edit_issuer_editor_pitch_path(offering)
        else
          flash.now.alert = "The following information is missing or invalid:"
          render :edit
        end
      end

      private

      def permitted_params
        return {} unless params[:pitch]

        params[:pitch].permit(
          pitch_sections_attributes: [
            :id, '_destroy', :title, :rank, content_items_attributes: [
              :id, '_destroy', :content_type, :rank, content_attributes: [
                :id, :body, :url, :html, :key, :expandable, carousel_images_attributes: [
                  :id, '_destroy', :key, :rank
                ]
              ]
            ]
          ]
        )
      end

      def assign_offering
        @offering ||= Offering.for_user(current_user)
          .includes(:company, pitch_sections: {content_items: :content})
          .find(params[:id])
      rescue ActiveRecord::RecordNotFound
        render_404
      end
      alias_method :offering, :assign_offering

      def assign_uploader
        @uploader = Pitch::Image.new.photo
        @uploader.success_action_status = '201'
      end
    end
  end
end

app/controllers/issuer/editor/questions_controller.rb
module Issuer
  module Editor
    class QuestionsController < BaseController

      before_action :assign_offering

      def edit
      end

      def update
        if offering.update_attributes(permitted_params)
          audit_form!
          flash.notice = "Your changes have been saved"
          redirect_to edit_issuer_editor_question_path(offering)
        else
          flash.now.alert = "The following information is missing or invalid:"
          render :edit
        end
      end

      private

      def permitted_params
        return {} unless params[:faq]

        params[:faq].permit(
          investor_faqs_attributes: [
            :id, '_destroy', :question, :answer, :rank
          ]
        )
      end

      def assign_offering
        @offering ||= Offering.for_user(current_user)
          .includes(:company, :investor_faqs)
          .find(params[:id])
      end
      alias_method :offering, :assign_offering

    end
  end
end

app/controllers/issuer/editor/stakeholders_controller.rb
module Issuer
  module Editor
    class StakeholdersController < BaseController

      before_action :assign_offering
      before_action :assign_uploader

      def edit
      end

      def update
        offering.update_attribute(:notable_investor_id, nil) # the next step will set it again if there is a new one
        if offering.update_attributes(permitted_params)
          audit_form!
          redirect_to edit_issuer_editor_stakeholder_path(offering)
          flash.notice = "Your changes have been saved"
        else
          flash.now.alert = "The following information is missing or invalid:"
          render 'edit'
        end
      end

      private

      def permitted_params
        return {} unless params[:stakeholders]

        params[:stakeholders].permit(
          team_members_attributes: [
            :id, :_destroy, :stakeholder_type_id, :full_name, :rank,
            :position, :bio, :linkedin_url, :twitter_url, :facebook_url,
            :website, :avatar_photo_key, :is_notable_investor
          ], investors_attributes: [
            :id, :_destroy, :stakeholder_type_id, :full_name, :rank,
            :position, :bio, :linkedin_url, :twitter_url, :facebook_url,
            :website, :avatar_photo_key, :is_notable_investor
          ]
        )
      end

      def assign_offering
        @offering ||= Offering.for_user(current_user)
        .includes(:stakeholders)
        .find(params[:id])
      end
      alias_method :offering, :assign_offering

      def assign_uploader
        @uploader = Stakeholder.new.avatar_photo
        @uploader.success_action_status = '201'
      end

    end
  end

end

app/views/issuer/editor/stakeholders/_form.html.haml
= simple_form_for(@offering, url: issuer_editor_stakeholder_path(@offering), as: :stakeholders, method: :put, html: { class: "row-fluid content-editor-form" }) do |f|
  %h4
    Founding Team Members
  %p
    = t('issuer.editor.team')
    .team-members-container.template-group
      = f.simple_fields_for :team_members do |builder|
        = render partial: 'template_team_member', locals: { f: builder }
      .row-fluid.content-creation.push-down-small
        .span11
          = add_section_button_tag('Add Team Member', f, :team_members, class: 'btn-dashed btn-full btn-plus')
  %h4
    Investors, Advisors, &amp; Board Members
  %p
    = t('issuer.editor.investor')
    %br
    = t('issuer.editor.notable_investor')
    .investors-container.template-group
      = f.simple_fields_for :investors do |builder|
        = render partial: 'template_investor', locals: { f: builder }
      .row-fluid.content-creation
        .span11
          = add_section_button_tag('Add Person', f, :investors, class: 'btn-dashed btn-full btn-plus')

app/views/issuer/editor/stakeholders/_template_investor.html.haml
.row-fluid.investor-fields.rankable.section
  .span11
    .well.well-plain.push-down-smallest
      .row-fluid
        .span3
          = f.input :avatar_photo, as: :image_upload, text: 'Select Photo', label: false, input_html: {accept: 'image/*', class: 'image-avatar uploadable'}

        .span9.left-padded-fields
          .row-fluid
            .span6
              = f.hidden_field :id
              = f.hidden_field :stakeholder_type_id, value: "investor"
              = f.hidden_field :rank, class: "rank"
              = f.hidden_field :_destroy, value: false, class: "destroy"
              = f.label :full_name, "Name"
              = f.text_field :full_name
            .span6
              = f.label :position
              = f.text_field :position
            .span12
              = f.label :bio
              = f.text_area :bio, rows: "10"
            .span6
              = f.label :linkedin_url, "LinkedIn"
              = f.input :linkedin_url, label: false
            .span6
              = f.label :twitter_url, "Twitter"
              = f.input :twitter_url, label: false
            .span6
              = f.label :website
              = f.input :website, label: false
            .span6
              = f.label :facebook_url, "Facebook"
              = f.input :facebook_url, label: false
  .span1
    = render partial: 'issuer/editor/vertical_controls', locals: {f: f}

app/views/issuer/editor/stakeholders/_template_team_member.html.haml
.row-fluid.team-member-fields.rankable.section
  .span11
    .well.well-plain.push-down-smallest
      .row-fluid
        .span3
          = f.input :avatar_photo, as: :image_upload, text: 'Select Photo', label: false, input_html: {accept: 'image/*', class: 'image-avatar uploadable'}

        .span9.left-padded-fields
          .row-fluid
            .span6
              = f.hidden_field :id
              = f.hidden_field :stakeholder_type_id, value: "team_member"
              = f.hidden_field :rank, class: "rank"
              = f.hidden_field :_destroy, value: false, class: "destroy"
              = f.label :full_name, "Name"
              = f.text_field :full_name
            .span6
              = f.label :position
              = f.text_field :position
            .span12
              = f.label :bio
              = f.text_area :bio, rows: "10"
            .span6
              = f.label :linkedin_url, "LinkedIn"
              = f.input :linkedin_url, label: false
            .span6
              = f.label :twitter_url, "Twitter"
              = f.input :twitter_url, label: false
            .span6
              = f.label :website
              = f.input :website, label: false
            .span6
              = f.label :facebook_url, "Facebook"
              = f.input :facebook_url, label: false
  .span1
    = render partial: 'issuer/editor/vertical_controls', locals: {f: f}

app/views/issuer/editor/stakeholders/edit.html.haml
= content_for(:page_title, "#{@offering.company.name} | Team Editor")

= content_for(:main_container_class) do
  full-width light-gray

.flash-notice= flash[:notice]
.flash-alert= flash[:alert]

#offering-editor
  .offering-editor#members-editor
    = render partial: 'issuer/editor/navigation', locals: { active_tab: :members }

    = render partial: 'form'

    = render partial: 'shared/file_upload_form', locals: {uploader: @uploader}