config/routes.rb
Flashfunders::Application.routes.draw do
  concern :showable_new do
    get :show, on: :member, action: :new
  end

  concern :showable_edit do
    get :show, on: :member, action: :edit
  end

  root to: 'home#show'

  get 'converted_show', to: 'home#converted_show'

  devise_for :users, controllers: { sessions: 'sessions', registrations: 'registrations', confirmations: 'confirmations', passwords: 'passwords', omniauth_callbacks: 'omniauth' }

  devise_scope :user do
    put '/users/confirm', to: 'confirmations#confirm', as: :user_confirm
    get '/users/log_me_out', to: 'sessions#log_me_out', as: :user_log_me_out
    get '/users/logout', to: 'sessions#logout', as: :user_logout

    namespace :api, defaults: { format: :json } do
      get '/users/session_info', to: '/sessions#session_info', as: :user_session_info
    end
  end

  get 'user/email_consent', to: 'email_consent#new'
  post 'user/email_consent', to: 'email_consent#create'
  get 'sign/:investment_uuid', to: 'docusign_bypass#sign'
  get 'issuer_sign/:investment_uuid', to: 'docusign_bypass#issuer_sign'
  get 'sign_success', to: 'docusign_bypass#success', as: :sign_success
  get 'sign_redirect', to: 'docusign_bypass#redirect', as: :sign_redirect
  get 'investment_agreement/:investment_uuid', to: 'docusign_bypass#agreement', as: :investment_agreement

  get '/impersonate/user/:user_id', to: 'impersonations#create', as: :impersonate
  delete '/impersonate/user/revert', to: 'impersonations#destroy', as: :revert_impersonate

  resource :issuer_applications, only: [:new, :create], concerns: [:showable_new] do
    get 'success'
    get 'recreate'
  end

  resource :dashboard, only: :show do
    resources :investments, only: [:index], controller: 'investments' do
      member do
        get :download_docs
        put :cancel_investment
      end
    end
    resources :conversations, only: [:index, :show, :create], controller: 'messages'
  end

  resource :subscriptions, only: [:create]
  get 'subscribe', to: 'subscriptions#new', as: :subscribe
  post 'dismiss', to: 'subscriptions#dismiss', as: :dismiss

  namespace :issuer do
    namespace :editor do
      resources :details, only: [:edit, :update], concerns: [:showable_edit]
      resources :pitches, only: [:edit, :update], concerns: [:showable_edit]
      resources :questions, only: [:edit, :update], concerns: [:showable_edit]
      resources :documents, only: [:edit, :update], concerns: [:showable_edit]
      resources :stakeholders, only: [:edit, :update], concerns: [:showable_edit]
    end
    resources :dashboard, controller: :dashboard, only: :show do
      get 'active_investments'
      get 'investment_activity', action: 'export_csv'
    end
    get 'change_context', controller: 'issuer'
  end

  resources :offering, controller: :offerings, only: :show do
    resource :investment_flow, controller: 'investment_flow/investments', except: [:destroy, :show] do
      resource :fund, controller: 'investment_flow/funds', only: [:new, :create, :edit, :update], concerns: [:showable_new] do
        get '/complete', action: 'complete'
      end
    end

    resource :investment, controller: 'invest/investments', except: [:destroy, :show] do
      get 'recreate'
      post '/update_payment', action: 'update_payment'
      post '/resend_verification', action: 'resend_verification'
    end
    namespace :invest do
      namespace :accreditation do
        resource :new, controller: :new, only: [:new, :create, :edit, :update], concerns: [:showable_new]
        resource :verified, controller: :verified, only: [:new, :create], concerns: [:showable_new]
      end
      resource :investment_profile, only: [:new, :create, :edit], concerns: [:showable_new]
      resource :investment_documents, only: [:show] do
        post '/accept', action: 'accept'
        get '/docusign_handler', action: 'docusign_handler'
        get '/docusign_redirect', action: 'docusign_redirect'
      end

      resource :fund, only: [:new, :create, :edit, :update], concerns: [:showable_new] do
        get '/complete', action: 'complete'
      end

    end

    resources :messages, controller: :offering_messages, only: [:create]
    resources :comment_forms, controller: :offering_comment_forms, only: [:create, :destroy]
    resource :follower, controller: :offering_followers, only: [:update, :destroy] do
      get 'follow', as: :redirect
    end
  end

  resources :third_party_qualifications, only: [:edit, :update], concerns: [:showable_edit] do
    get :decline, on: :member
  end

  resource :browse, only: :show
  resources :contact_forms, only: :create

  get '/terms', to: 'static#tos', as: :terms
  get '/terms_of_use', to: 'static#tos', as: nil
  get '/privacy', to: 'static#privacy', as: :privacy
  get '/privacy_policy', to: 'static#privacy', as: nil
  get '/email_disclaimer', to: 'static#email_disclaimer'
  get '/email_disclaimer_to_investor', to: 'static#email_disclaimer_to_investor'
  get '/email_disclaimer_to_issuer', to: 'static#email_disclaimer_to_issuer'
  get '/cip_notice', to: 'static#cip_notice'
  get '/unsubscribe', to: 'static#unsubscribe', as: :unsubscribe
  get '/contact', to: 'static#contact', as: :contact
  get '/get_started', to: 'static#get_started', as: :get_started
  get '/faq', to: 'static#faq_investor', as: :faq
  get '/team', to: 'static#team', as: :team
  get '/press', to: 'static#press', as: :press
  get '/electronic_consent', to: 'static#econsent', as: :econsent
  get '/sitemap', to: 'static#sitemap', as: :site_map

  if Rails.env.production?
    get '/blog', to: redirect('http://blog.flashfunders.com'), as: :blog
  else
    get '/blog', to: redirect('http://blog.flashdough.com'), as: :blog
  end
  get '/embedded_footer', to: 'iframeable#footer'
  get '/embedded_header', to: 'iframeable#header'

  get '/flashfundersinsider', to: redirect("#{ENV['HUBSPOT_LANDING_DOMAIN']}/flashfundersinsider"), as: :digital_marketing_landing_page

  get '/what_is_flashfunders', to: 'static#investors', as: :what_is_flashfunders

  get '/investors', to: 'static#investors', as: :investors
  get '/investor_hub', to: 'static#investors', as: :investor_hub
  get '/investor_faq', to: 'static#faq_investor', as: :investor_faq
  get '/faq/investor', to: 'static#faq_investor', as: :faq_investor

  get '/startups', to: 'static#startups', as: :startups
  get '/startup_hub', to: 'static#startups', as: :startup_hub
  get '/startup_faq', to: 'static#faq_startup', as: :startup_faq
  get '/faq/startup', to: 'static#faq_startup', as: :faq_startup

  # obsoleted paths redirection
  get '/how_to_invest', to: redirect('faq/investor#how_to_invest_flow')
  get '/raise_capital', to: redirect('startups')
  get '/documents/Investors', to: redirect('faq/investor#general')
  get '/startup_requirements', to: redirect('faq/startup#general-what-are-the-requirements-to-raise-capital-on-flashfunders')
  get '/investor_terms', to: redirect('faq/investor#investor_requirements_and_rights')
  get '/investor_benefits', to: redirect('faq/investor#benefits_risks')
  get '/startup_terms', to: redirect('faq/startup#fundraising_details')
  get '/investor_how_to_invest', to: redirect('faq/investor#how_to_invest_flow')

  namespace :api, defaults: { format: :json } do
    resources :offerings, only: :show

    namespace :issuer do
      resources :offerings, only: :index
      namespace :analytics do
        get '/get_data', to: '/issuer/analytics#get_data'
      end
    end

    get '/regions', to: '/static#regions', as: :regions
    get '/lookup_routing_number', to: '/static#lookup_routing_number', as: :lookup_routing_number
  end

  get '/robots.txt', to: 'home#robots'

  unless Rails.env.production?
    get '/style_guide', to: 'static#style_guide', as: :style_guide
    get '/honeybadger', to: 'honeybadger#blow_up'
  end

  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_error'

  # This is a catch-all route - leave it at the bottom of the routes file so it
  # doesn't clobber any legitimate routes
  get '*path', to: 'offerings#vanity_show', constraints: OfferingsVanityConstraints.new, as: 'offering_vanity'
end

app/controllers/invest/investments_controller.rb
module Invest
  class InvestmentsController < InvestController
    include InvestmentSummaryAssignment
    prepend_before_action :save_recreate_params, only: :create

    skip_before_action :authenticate_user!, only: [:new, :create]
    skip_before_action :redirect_to_correct_path_for_state, only: [:update_payment, :resend_verification]

    before_action :set_offering_presenter

    def new
      @investor_investment = InvestorInvestmentForm.new({ offering_id: @offering.id })
      @offering_presenter = OfferingPresenter.new(@offering)
      if current_user
        offering_follower = OfferingFollower.find_or_initialize_by(offering_id: @offering_presenter.offering_id, user: current_user)
        offering_follower.follow_as!(:investor)
      end
      @unrounded_investment_amount = 0
      @investment_amount = 0
      @investment_shares = 0
      @investment_percent_ownership = 0
      render investment_form, locals: { path: 'commit' }
    end

    def create
      @investor_investment = InvestorInvestmentForm.new(form_params, investor_investment_form_validator)

      if investor_investment_form_validator.valid?
        authenticate_user!
        offering_follower = OfferingFollower.find_or_initialize_by(offering_id: @offering_presenter.offering_id, user: current_user)
        offering_follower.follow_as!(:investor)

        @investment = @investor_investment.create

        audit_form!

        redirect_for_investment
      else
        render_errors('commit', @investor_investment)
      end
    end

    def recreate
      unless !investment.persisted? && super
        redirect_for_investment
      end
    end

    def edit
      @investor_investment = InvestorInvestmentForm.new({ offering_id: @offering.id, investment_id: @investment.id })
      @offering_presenter = OfferingPresenter.new(offering)

      @unrounded_investment_amount = @investment.amount || 0
      @investment_amount = @investment.amount || 0
      @investment_shares = @investment.shares || 0
      @investment_percent_ownership = @investment.percent_ownership || 0

      render investment_form, locals: { path: 'edit' }
    end

    def update
      @investor_investment = InvestorInvestmentForm.new(form_params.merge({ investment_id: @investment.id }), investor_investment_form_validator)

      if investor_investment_form_validator.valid?
        @investor_investment.update

        audit_form!

        redirect_for_investment
      else
        render_errors('edit', @investor_investment)
      end
    end

    def update_payment
      sent = params[:yes_or_no] == 'true'
      if sent
        @investment.send_funds! if @investment.funding_method_selected?
      else
        @investment.select_funding_method! if @investment.funds_sent?
      end
      result = { payment_sent: sent }
      result.merge({ kind: @investment.funding_method }) if @investment.funding_method.present?
      render json: result
    end

    def resend_verification
      @investment.resend_verification_email
      render json: { sent: true }
    end

    private

    def save_recreate_params
      store_recreate_to_session(recreate_offering_investment_url(params[:offering_id]),
                                { 'investment' => params['investment'] })
    end

    def render_errors(path, form)
      Rails.logger.warn(form.errors.first)
      present_invalid_investment(permitted_params[:unrounded_investment_amount])
      render investment_form, locals: { path: path }
    end

    def investment_form
      @offering_presenter.convertible? ? 'investment_notes_form' : 'investment_stock_form'
    end

    def permitted_params
      params.require(:investment).permit(
        :investment_amount,
        :investment_shares,
        :investment_percent_ownership,
        :unrounded_investment_amount)
    end

    def form_params
      {
        user: current_user,
        offering_id: @offering.id,
        investment_amount: investor_investment_calculator.projected_cost,
        investment_shares: investor_investment_calculator.projected_shares,
        investment_percent_ownership: investor_investment_calculator.projected_percent_ownership
      }
    end

    def present_invalid_investment(unrounded_investment_amount)
      @unrounded_investment_amount = unrounded_investment_amount
      @investment_amount = 0
      @investment_shares = 0
      @investment_percent_ownership = 0
    end

    def offering_presenter
      @offering_presenter ||= OfferingPresenter.new(@offering)
    end
    alias :set_offering_presenter :offering_presenter

    def investor_investment_calculator
      @calculator ||= InvestorInvestmentCalculator.get_calc(permitted_params[:unrounded_investment_amount], offering_presenter)
    end

    def investor_investment_form_validator
      @validator ||= InvestorInvestmentFormValidator.new(permitted_params, investor_investment_calculator, offering_presenter)
    end

    def audit_params
      {
        desired_investment_amount: permitted_params[:unrounded_investment_amount],
        displayed_investment_amount: permitted_params[:investment_amount],
        actual_investment_amount: investor_investment_calculator.projected_cost.to_s,
        displayed_investment_shares: permitted_params[:investment_shares],
        actual_investment_shares: investor_investment_calculator.projected_shares.to_s,
        displayed_investment_percent_ownership: permitted_params[:investment_percent_ownership],
        actual_investment_percent_ownership: investor_investment_calculator.projected_percent_ownership.to_s
      }
    end

    def additional_javascript_vars
      gon.investment_form = investment_form

    end

  end
end

app/controllers/investment_flow/investments_controller.rb
module InvestmentFlow

  class InvestmentsController < InvestController
    include AnalyticsTracker

    before_action :authenticate_user!

    def new
      @form ||= InvestmentFlowForm.new(form_params, @offering, @investment)
      track_facebook_pixel(@offering.facebook_pixel_id, 'AddToCart')
      track_google_analytics(@offering.google_tracking_id)
      track_google_adwords(@offering.google_adwords_conversion_id, @offering.google_adwords_conversion_label)
    end

    def create
      @form = InvestmentFlowForm.new(valid_params, @offering, @investment)
      if @form.valid?
        @form.create_or_update_investment(current_user.id)
        audit_form!
        redirect_for_investment
      else
        render :new
      end
    end

    def edit
      @form ||= InvestmentFlowForm.new(form_params, @offering, @investment)
      render :new, locals: { path: 'edit' }
    end

    def audit_params
      valid_params.merge({ shares: @investment.shares,
                           percent_ownership: @investment.percent_ownership })
    end

    private

    def internal_investments_sum
      @internal_investments_sum ||= OfferingInvestments.new(nil, current_user).reg_c_investments_total(@investment.id)
    end

    def reg_c_cutoff
      @reg_c_cutoff ||= 20000
    end

    def reg_c_min
      @offering_presenter = OfferingPresenter.new(@offering)
      @offering_presenter.minimum_investment_amount
    end

    def reg_s_min
      reg_c_min
    end

    def form_params
      {}.tap do |h|
        h[:internal] = internal_investments_sum
        h[:international] = current_user.international?
        h[:reg_c_cutoff] = reg_c_cutoff
        h[:reg_c_min] = reg_c_min
        h[:reg_s_min] = reg_s_min
        h[:amount] = @investment.amount
        unless @investment.calc_data.blank?
          h[:selector] = @investment.reg_selector
          h[:international] = @investment.reg_s_investor?
          h[:income] = @investment.reg_c_income
          h[:net_worth] = @investment.reg_c_net_worth
          h[:external] = @investment.reg_c_external
        end
      end
    end

    def valid_params
      {}.tap do |h|
        params.require(:investment).permit(*InvestmentFlowForm::ATTRIBUTES).each do |k, v|
          if InvestmentFlowForm::ALPHA_ATTRIBUTES.include?(k.to_sym)
            h[k] = v
          else
            h[k] = v.gsub(/[^0-9.-]/, '').to_f
          end
        end
        h[:server_internal] = internal_investments_sum
        h[:server_reg_c_cutoff] = reg_c_cutoff
      end
    end

  end

end

app/controllers/investments_controller.rb
class InvestmentsController < ApplicationController
  include OfferingHelper

  def index
    @investments = Investment.investment_order(current_user).map do |investment|
      offering = investment.offering
      company = offering.company
      offering_presenter = OfferingPresenter.new(offering)
      investment_presenter = InvestmentPresenter.new(investment)
      investment_hash = {
        investment_summary: InvestorInvestmentSummary.new(investment, offering),
        investment: investment_presenter,
        campaign: offering_presenter,
        funding_detail: investment_presenter.funding_detail_domestic,
        funding_international_detail: investment_presenter.funding_detail_international,
        social: SocialPresenterFactory.build(offering_vanity_url(offering_presenter), t('show_campaign.social.twitter.account'), company.name, offering.tagline),
      }
      investment_hash
    end
  end

  def download_docs
    investment = Investment.find(params[:id])
    send_data investment.download_docs_stream, type: 'application/octet-stream', disposition: 'inline', filename: "Investment Agreement Documents #{investment.offering.corporate_name}.pdf"
  end

  def cancel_investment
    investment = Investment.find_by(id: params[:id], user_id: current_user&.id)
    if investment && InvestmentPresenter.new(investment).can_cancel_investment?
      investment.cancel!
      redirect_to action: :index
    else
      render :index
    end
  end

end

app/views/investment_flow/investments/_flow_selector.html.haml
#flow-selector.invest-panel
  - if @offering.reg_c_only?
    %a{ href: '#reg-c-panel', data: {toggle: 'tab'} }
  - else
    .tab-box.row-fluid
      .span12.centered
        %h3.header= t('investment_flow.invest.flow_selector.title')
      %ul.selections#reg_c_or_reg_d
        %li.span6.tab.short
          %a.span12{ href: '#reg-c-panel', data: {toggle: 'tab'} }
            .title= t('investment_flow.invest.flow_selector.reg_c_button.text', cutoff: number_to_currency(@reg_c_cutoff, precision: 0))
        %li.span6.tab.short
          %a.span12{ href: '#reg-d-panel', data: {toggle: 'tab'} }
            - unless @form.international
              .subtitle= t('investment_flow.invest.flow_selector.reg_d_button.title')
            .title= t('investment_flow.invest.flow_selector.reg_d_button.text', cutoff: number_to_currency(@reg_c_cutoff, precision: 0))

      %ul
        %li.span6.long
          .caption= t('investment_flow.invest.flow_selector.reg_c_button.caption',
                      link: link_to(t('investment_flow.invest.flow_selector.reg_c_button.link_text'), "#{faq_investor_path}#investor_requirements_and_rights-is-there-a-difference-between-the-kinds-of-stock-that-reg-cf-and-reg-d-investors-purchase")).html_safe
        %li.span6.long
          - if @form.international
            .caption= t('investment_flow.invest.flow_selector.reg_d_button.intl_caption',
                      link: link_to(t('investment_flow.invest.flow_selector.reg_d_button.link_text'), '#')).html_safe
          - else
            .caption= t('investment_flow.invest.flow_selector.reg_d_button.caption',
                      link: link_to(t('investment_flow.invest.flow_selector.reg_d_button.link_text'), "#{faq_investor_path}#investor_requirements_and_rights-is-there-a-difference-between-the-kinds-of-stock-that-reg-cf-and-reg-d-investors-purchase")).html_safe

  #reg-c-panel.tab-pane
    = render partial: 'reg_c_calculator', locals: { tabindex: tabindex }

  #reg-d-panel.tab-pane

app/views/investment_flow/investments/_investment_calculator.html.haml
#investment-flow-calculator{ style: 'display: none;' }
  = simple_form_for @form, as: :investment, url: offering_investment_flow_path(@offering), method: :post, html: { autocomplete: 'off' } do |f|
    =f.input :reg_c_output, as: :hidden
    =f.input :selector, as: :hidden
    =f.input :income, as: :hidden
    =f.input :net_worth, as: :hidden
    =f.input :external, as: :hidden
    =f.input :internal, as: :hidden
    =f.input :reg_c_cutoff, as: :hidden
    =f.input :reg_c_min, as: :hidden
    =f.input :reg_s_min, as: :hidden
    =f.input :international, as: :hidden

    .invest-panel
      .row-fluid.span12.centered
        %h3.header
          = t('investment_flow.invest.flow_selector.amount_calculator.title')

      .row-fluid
        .span6.offset3.centered
          =f.input :amount, as: :string, label: false, required: false,
                  input_html: { tabindex: tabindex.next,
                                onkeypress: 'return floatInput(event);',
                                onkeyup: 'return handleUserInput(event);',
                                data: { calc_args: InvestorInvestmentCalculator.get_calc(0, OfferingPresenter.new(@offering)).javascript_args }}
      .row-fluid
        .span8.offset2.centered
          .invest-limit
      .row-fluid
        .span8.offset2.centered
          .owner-percent
            = 'Own'
            %span#percent-ownership
            = 'of the company for'
            %span#projected-cost
            = 'at'
            %span#share-price
            = 'per share'

    #form-buttons
      .row-fluid
        .span6
          =link_to t('investment_flow.invest.flow_selector.amount_calculator.buttons.cancel'), |
            path == 'edit' ? new_offering_investment_flow_path(@offering) : offering_path(@offering), |
            class: "btn btn-block base-btn btlarge", tabindex: tabindex.next + 1
        .span6
          =button_tag(t('investment_flow.invest.flow_selector.amount_calculator.buttons.save'), class: "btn btn-primary btn-block btlarge", tabindex: tabindex.next - 1, disabled: true)
          #spinner.centered.btn-block.btlarge.la-ball-clip-rotate.la-sm.hidden
            .btn-spinner

app/views/investment_flow/investments/_reg_c_calculator.html.haml
#reg-c-calculator
  .centered
    =image_tag('calculator_icon.png')
    %h4.header= t('investment_flow.invest.flow_selector.reg_c_calculator.title')

  .row-fluid
    .span8.title
      = t('investment_flow.invest.flow_selector.reg_c_calculator.income', income_popover_text: t('investment_flow.invest.flow_selector.reg_c_calculator.income_popover_text')).html_safe
    .span4
      %input{id: 'income', type: 'text', onkeyup: 'return handleUserInput(event);', onkeypress: 'return floatInput(event);', placeholder: '$0', tabindex: tabindex.next}
  .row-fluid
    .span8.title
      = t('investment_flow.invest.flow_selector.reg_c_calculator.worth', worth_popover_text: t('investment_flow.invest.flow_selector.reg_c_calculator.worth_popover_text')).html_safe
    .span4
      %input{id: 'net_worth', type: 'text', onkeyup: 'return handleUserInput(event);', onkeypress: 'return floatInput(event);', placeholder: '$0', tabindex: tabindex.next}
  .row-fluid#reg-c-limit
    .span8.title= t('investment_flow.invest.flow_selector.reg_c_calculator.limit')
    .span4.computed-value= '$2,000'
  .row-fluid
    .span8
      .span12.title= t('investment_flow.invest.flow_selector.reg_c_calculator.external.title',
      popover: t('investment_flow.invest.flow_selector.reg_c_calculator.external.popover_text',
      link: link_to(t('investment_flow.invest.flow_selector.reg_c_calculator.external.link_text'),
      "#{faq_investor_path}#investor_requirements_and_rights-who-can-invest"))).html_safe
      .span12.subtitle= t('investment_flow.invest.flow_selector.reg_c_calculator.external.subtitle')
    .span4
      %input{id: 'external', type: 'text', onkeyup: 'return handleUserInput(event);', onkeypress: 'return floatInput(event);', placeholder: '$0', tabindex: tabindex.next}
  .row-fluid
    .span8
      .title= t('investment_flow.invest.flow_selector.reg_c_calculator.internal.title')
      .subtitle= t('investment_flow.invest.flow_selector.reg_c_calculator.internal.subtitle')
    .span4.computed-value#previous_investments_sum= "#{number_to_currency(@internal_investments_sum.ceil, precision: 0)}"
  .row-fluid#reg-c-total
    .span8.title= t('investment_flow.invest.flow_selector.reg_c_calculator.total')
    .span4.computed-value= '$0'
  .row-fluid
    .span8
      .disclaimer= t('investment_flow.invest.flow_selector.reg_c_calculator.caption')
    .span4
      .disclaimer= link_to(t('investment_flow.invest.flow_selector.reg_c_calculator.how_link'), "#{faq_investor_path}#investor_requirements_and_rights-why-are-there-investor-limits")

app/views/investment_flow/investments/new.html.haml
= content_for(:page_title, 'Investor Calculator')

- content_for(:main_container_class) do
  full-width gray

= content_for(:step_description) do
  .step-title.centered
    %h2= t('investment_flow.invest.title', company: @offering.company.name)

- tabindex = Counter.new(2)

#investment-flow-container
  = render partial: 'flow_selector', locals: { tabindex: tabindex }
  = render partial: 'investment_calculator', locals: { path: 'new', tabindex: tabindex }